import type {
  MenuCategory,
  MenuItem,
  OrderStatus,
  Table,
} from "@/types";

export const ORDER_STATUSES: OrderStatus[] = [
  "pending",
  "accepted",
  "preparing",
  "ready",
  "served",
  "completed",
  "cancelled",
];

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "cat-appetizers",
    restaurantId: "rest-1",
    name: "Appetizers",
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-main",
    restaurantId: "rest-1",
    name: "Main Course",
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-desserts",
    restaurantId: "rest-1",
    name: "Desserts",
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-beverages",
    restaurantId: "rest-1",
    name: "Beverages",
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-specials",
    restaurantId: "rest-1",
    name: "Specials",
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "item-1",
    restaurantId: "rest-1",
    categoryId: "cat-appetizers",
    name: "Garlic Parmesan Fries",
    price: 1099,
    description: "Crispy fries tossed with garlic butter and parmesan.",
    imageUrl: "/placeholders/menu-fries.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-2",
    restaurantId: "rest-1",
    categoryId: "cat-appetizers",
    name: "Spicy Chicken Wings",
    price: 1599,
    description: "House sauce, served hot with a side of ranch.",
    imageUrl: "/placeholders/menu-wings.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-3",
    restaurantId: "rest-1",
    categoryId: "cat-appetizers",
    name: "Crispy Calamari",
    price: 1799,
    description: "Lightly battered rings with lemon zest & marinara.",
    imageUrl: "/placeholders/menu-calamari.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-4",
    restaurantId: "rest-1",
    categoryId: "cat-appetizers",
    name: "Bruschetta Trio",
    price: 1299,
    description: "Tomato basil, olive tapenade, and roasted pepper bites.",
    imageUrl: "/placeholders/menu-bruschetta.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-5",
    restaurantId: "rest-1",
    categoryId: "cat-appetizers",
    name: "Truffle Parmesan Fries",
    price: 1399,
    description: "Truffle aioli, parmesan snow, and cracked pepper.",
    imageUrl: "/placeholders/menu-truffle-fries.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-6",
    restaurantId: "rest-1",
    categoryId: "cat-main",
    name: "Classic Cheeseburger",
    price: 1299,
    description: "Smash patty, cheddar, house sauce, pickles, and onions.",
    imageUrl: "/placeholders/menu-burger.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-7",
    restaurantId: "rest-1",
    categoryId: "cat-main",
    name: "Margherita Pizza",
    price: 1899,
    description: "Fresh mozzarella, basil, and crushed tomatoes on a thin crust.",
    imageUrl: "/placeholders/menu-pizza.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-8",
    restaurantId: "rest-1",
    categoryId: "cat-main",
    name: "BBQ Brisket Sandwich",
    price: 1699,
    description: "Smoked brisket, tangy BBQ, coleslaw, and brioche.",
    imageUrl: "/placeholders/menu-brisket.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-9",
    restaurantId: "rest-1",
    categoryId: "cat-main",
    name: "Baja Fish Tacos",
    price: 1499,
    description: "Crispy fish, cabbage crunch, lime crema, and pico de gallo.",
    imageUrl: "/placeholders/menu-tacos.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-10",
    restaurantId: "rest-1",
    categoryId: "cat-main",
    name: "Chicken Alfredo",
    price: 2099,
    description: "Creamy parmesan alfredo with grilled chicken and parsley.",
    imageUrl: "/placeholders/menu-alfredo.png",
    isAvailable: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-11",
    restaurantId: "rest-1",
    categoryId: "cat-main",
    name: "Veggie Power Bowl",
    price: 1599,
    description: "Roasted seasonal veg, quinoa, avocado, and citrus vinaigrette.",
    imageUrl: "/placeholders/menu-power-bowl.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-12",
    restaurantId: "rest-1",
    categoryId: "cat-desserts",
    name: "Chocolate Lava Cake",
    price: 899,
    description: "Warm molten center with vanilla bean ice cream.",
    imageUrl: "/placeholders/menu-lavacake.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-13",
    restaurantId: "rest-1",
    categoryId: "cat-desserts",
    name: "Crème Brûlée",
    price: 1099,
    description: "Silky custard with caramelized sugar crackle.",
    imageUrl: "/placeholders/menu-creme-brulee.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-14",
    restaurantId: "rest-1",
    categoryId: "cat-desserts",
    name: "Strawberry Shortcake",
    price: 949,
    description: "Fresh strawberries, whipped cream, and vanilla sponge.",
    imageUrl: "/placeholders/menu-shortcake.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-15",
    restaurantId: "rest-1",
    categoryId: "cat-desserts",
    name: "Salted Caramel Cheesecake",
    price: 1199,
    description: "Creamy cheesecake with salted caramel swirl and crunch.",
    imageUrl: "/placeholders/menu-cheesecake.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-16",
    restaurantId: "rest-1",
    categoryId: "cat-beverages",
    name: "House Lemonade",
    price: 499,
    description: "Fresh-squeezed lemonade, lightly sweetened.",
    imageUrl: "/placeholders/menu-lemonade.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-17",
    restaurantId: "rest-1",
    categoryId: "cat-beverages",
    name: "Sparkling Citrus Soda",
    price: 449,
    description: "Bright citrus bubbles with a crisp finish.",
    imageUrl: "/placeholders/menu-soda.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-18",
    restaurantId: "rest-1",
    categoryId: "cat-beverages",
    name: "Cold Brew Coffee",
    price: 599,
    description: "Slow-steeped coffee with a smooth, low-acid taste.",
    imageUrl: "/placeholders/menu-cold-brew.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-19",
    restaurantId: "rest-1",
    categoryId: "cat-beverages",
    name: "Iced Matcha Latte",
    price: 649,
    description: "Ceremonial matcha blended with vanilla oat milk.",
    imageUrl: "/placeholders/menu-matcha-latte.png",
    isAvailable: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-20",
    restaurantId: "rest-1",
    categoryId: "cat-beverages",
    name: "Thai Iced Tea",
    price: 629,
    description: "Creamy Thai tea with sweet spice notes and ice.",
    imageUrl: "/placeholders/menu-thai-tea.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-21",
    restaurantId: "rest-1",
    categoryId: "cat-specials",
    name: "Chef’s Special Ramen",
    price: 2199,
    description: "Rich broth, tender noodles, and rotating chef toppings.",
    imageUrl: "/placeholders/menu-ramen.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-22",
    restaurantId: "rest-1",
    categoryId: "cat-specials",
    name: "Seasonal Peach Salad",
    price: 1399,
    description: "Peaches, arugula, feta, candied walnuts, and balsamic glaze.",
    imageUrl: "/placeholders/menu-peach-salad.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-23",
    restaurantId: "rest-1",
    categoryId: "cat-specials",
    name: "Surf & Turf Mini Skewers",
    price: 2599,
    description: "Grilled shrimp & beef bites with garlic herb butter.",
    imageUrl: "/placeholders/menu-skewers.png",
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const TABLES: Table[] = Array.from({ length: 10 }).map((_, idx) => {
  const n = idx + 1;
  const now = new Date().toISOString();
  return {
    id: `table-${n}`,
    restaurantId: "rest-1",
    name: `T${n}`,
    seats: n <= 3 ? 2 : n <= 6 ? 4 : 6,
    status: n === 2 ? "occupied" : n === 4 ? "reserved" : "available",
    createdAt: now,
    updatedAt: now,
  };
});

