from django.urls import path

from . import views

urlpatterns = [
    path("health", views.health),
    path("owner/plans", views.owner_plan_list),
    path("owner/auth/request-otp", views.owner_request_otp),
    path("owner/auth/verify-otp", views.owner_verify_otp),
    path("owner/auth/login", views.owner_login),
    path("owner/payments/session", views.owner_payment_session),
    path("owner/payments/callback", views.owner_payment_callback),
    path("owner/payments/status", views.owner_payment_status),
    path("owner/onboarding/setup", views.owner_setup),
    path("staff/auth/login", views.staff_login),
    path("staff/context", views.staff_context),
    path("staff/config", views.staff_config),
    path("staff/menu", views.staff_menu),
    path("staff/menu/categories", views.staff_menu_categories),
    path("staff/menu/items", views.staff_menu_items),
    path("staff/menu/items/<uuid:item_id>", views.staff_menu_item_detail),
    path("staff/tables", views.staff_tables),
    path("staff/tables/<uuid:table_id>", views.staff_table_detail),
    path("staff/orders", views.staff_orders),
    path("staff/orders/<uuid:order_id>", views.staff_order_detail),
    path("staff/reports", views.staff_reports),
    path("staff/devices/printer", views.staff_printer),
    path("staff/devices/printer/test", views.staff_printer_test),
    path("staff/notifications/waiter-call", views.staff_waiter_call),
    path("staff/sync/bootstrap", views.sync_bootstrap),
    path("staff/sync/pull", views.sync_pull),
    path("staff/sync/push", views.sync_push),
    path("staff/print-jobs/ack", views.print_job_ack),
    path("restaurants/<uuid:restaurant_id>/outlets/<uuid:outlet_id>/bootstrap", views.public_outlet_bootstrap),
    path("restaurants/<uuid:restaurant_id>/outlets/<uuid:outlet_id>/waiter-call", views.public_waiter_call),
    path("outlets/<uuid:outlet_id>/menu", views.public_menu),
    path("outlets/<uuid:outlet_id>/orders", views.public_order_create),
    path("outlets/<uuid:outlet_id>/orders/<uuid:order_id>", views.public_order_detail),
]
